news:
    path:     /
    defaults: { _controller: "MMIMMIBundle:news:index" }

news_show:
    path:     /{id}/show
    defaults: { _controller: "MMIMMIBundle:news:show" }

news_new:
    path:     /new
    defaults: { _controller: "MMIMMIBundle:news:new" }

news_create:
    path:     /create
    defaults: { _controller: "MMIMMIBundle:news:create" }
    requirements: { _method: post }

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "MMIMMIBundle:news:edit" }

news_update:
    path:     /{id}/update
    defaults: { _controller: "MMIMMIBundle:news:update" }
    requirements: { _method: post|put }

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "MMIMMIBundle:news:delete" }
    requirements: { _method: post|delete }
