<?php

namespace MMI\MMIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * newsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newsRepository extends EntityRepository
{
}
